---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  chart:
    spec:
      chart: metrics-server
      version: 6.x.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 6h
  targetNamespace: kube-system
  values:
    hostNetwork: true
    extraArgs:
      kubelet-preferred-address-types: InternalIP
      kubelet-insecure-tls: true
    replicas: 2
    podDisruptionBudget:
      enabled: true
      minAvailable: 1 